// Projecteuler.net/problem=2
// Solved by John Smalley on 10-18-2015
/*Even Fibonacci Numbers
Problem 2
Published on Friday, 19th October 2001, 06:00 pm; Solved by 412335; 
Difficulty rating: 5%

Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms 
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.

*/

// variables
var sum = 2;
var sequence = [1,2];
var i = 1;


do {
	// increment the counter by 1
	i++;

	// stores the next Fibonacci sequence in the sequence
	sequence[i] = sequence[i-2] + sequence[i-1];


	// checks if the Fibonacci sequence is even and if so, adds to the sum
	if (sequence[i] % 2 === 0) {
		sum += sequence[i];
	}

	// continue the while loop for as long as a Fibonacci sequence number
	// does not exceed 4,000,000
} while (sequence[i] < 4000000);

// prints the sum of the even-valued terms
console.log(sum);
